#[test]
fn did_something_horrible_happen() {
    assert_eq!(2 + 2, 4);
}
